openapi: 3.0.1
info:
  title: API - Users
  version: 1.0.0
  description: Documentación de los endpoints de usuarios

paths:
  /api/users:
    get:
      summary: Obtener todos los usuarios
      tags:
        - Users
      responses:
        "200":
          description: Lista de usuarios obtenida exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
        "500":
          description: Error interno del servidor
    post:
      summary: Crear un nuevo usuario
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        "201":
          description: Usuario creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  payload:
                    $ref: '#/components/schemas/User'
        "400":
          description: Datos inválidos

  /api/users/{uid}:
    put:
      summary: Actualizar un usuario por ID
      tags:
        - Users
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
          description: ID del usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        "200":
          description: Usuario actualizado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "404":
          description: Usuario no encontrado
    delete:
      summary: Eliminar un usuario por ID
      tags:
        - Users
      parameters:
        - in: path
          name: uid
          required: true
          schema:
            type: string
          description: ID del usuario
      responses:
        "200":
          description: Usuario eliminado exitosamente
        "404":
          description: Usuario no encontrado

components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
          description: id autogenerado por mongo
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electrónico del usuario
        password:
          type: string
          description: Contraseña encriptada
        role:
          type: string
          enum: [user, admin]
          description: Rol del usuario
        pets:
          type: array
          items:
            type: string
            description: IDs de mascotas adoptadas
      example:
        _id: "64f8d2cbd2b123456789abcd"
        first_name: "Dayana"
        last_name: "Blas"
        email: "dayana@example.com"
        password: "$2a$10$5dNksdfQWERTYencriptado"
        role: "user"
        pets:
          - "64f8e7cbd2b987654321abcd"

    createUser:
      type: object
      properties:
        first_name:
          type: string
          description: Nombre del usuario
        last_name:
          type: string
          description: Apellido del usuario
        email:
          type: string
          description: Correo electrónico
        password:
          type: string
          description: Contraseña (se encriptará automáticamente)
        role:
          type: string
          enum: [user, admin]
          description: Rol del usuario
      required:
        - first_name
        - last_name
        - email
        - password
